appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: CEDK0KKnvpG0rP5eoVOFYAUSWvQ59Yhr3gAgscYuDfRFzsI0rnOpO2kFHG4Jk3bVjBLS/kAdbFtPuoT2MB+K9QMgUG8MeF3Rjgwr7vLx1LXbSjfxmO8+S0tOTJc+D79n6p6gzuu7ckSu7I9p5+lVT1/qt/VS9OWX+CLuxGg0vYLPujZyIesNd4lFCCLp3dkwTTZ4YEaKQRW36Fx1QtXe+IymQmff7va4t0PKD014VVUrJtk/wtdh0Q3PKMT0H6MSh0MIvMebfkPZSQLFyE2gwAhGFIu6MYrZ/8nuK2uhsY0xruOQfU0CmL1KFfqBO6xnEmNrKatAXSPdrZ2eSgv+IO95ZjvChQh1lBygzh3BjYLnunBCVmIHbdMYeEeP6MdpE4eOTB6fz/DoaxQki1LqwvwgtD7xsrpFb5QhI4TUzOqQHPqBwKdwZ2MHYKNg4ytWGMp4EN3gELNiPqD8SivzFBkY3ACXwWNg/PEpmiNFdgXHw5bgtaRdEXpRKHqtRdpxZq0coU6+87k5dB18sybSv5C33NRHZ7ea5iAt0dopCEBBWOD0txcMqlD0ozbRPgaf0Kk7VxH3pyNYwATN9YPXQHvYQoi/JeYLLNnfpYpusslBoBxdOMQCb3A64vjwTA2LUwnEXflyNKJVhVoHDf/542GkRRrE+QcBj4KG64jQl8k=
